### ISSUE TITLE
block_merge_sort.cuh(169): error: expected a ")"

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/cub#396]
I am seeing this error when compiling PyTorch with the latest main branch of cub. I don't know what is the root cause of this problem, because line 169 looks correct to me.

**Comment by zasdfgbnm** [comment]
@jeychandar This should have already been resolved by the latest PyTorch. Could you try a newer version of PyTorch?

**Comment by jeychandar** [comment]
@zasdfgbnm Thank you for your response sir. I will check it out :).

**Comment by jeychandar** [comment]
@zasdfgbnm Hi sir I have updated to latest version but still getting the same error.
pip show torch
Name: torch
Version: 2.0.1

The error is:
<command-line>: warning: ISO C++11 requires whitespace after the macro name
<command-line>: warning: ISO C++11 requires whitespace after the macro name
<command-line>: warning: ISO C++11 requires whitespace after the macro name
/usr/local/cuda/targets/x86_64-linux/include/cub/agent/../block/block_merge_sort.cuh(169): error: expected a "," or ">"

1 error detected in the compilation of "/home/praveen/livox_centerpoint/src/centerpoint-livox/src/postprocess.cu".
CMake Error at centerpoint_generated_postprocess.cu.o.Debug.cmake:280 (message):
  Error generating file
  /home/praveen/livox_centerpoint/build/centerpoint/CMakeFiles/centerpoint.dir/src/./centerpoint_generated_postprocess.cu.o

**Comment by zasdfgbnm** [comment]
Then I think you have the described problem either at your `postprocess.cu` or at `centerpoint_generated_postprocess.cu`? I think you would need to review your codebase to see if you have something like `#define NUM_THREADS`

**Comment by zasdfgbnm** [comment]
On the other hand @senior-zero, should cub change the coding style to avoid using all-upper case constants? I understand that I should blame the code that defines the conflicting macro, instead of cub, for having this issue, but in general, ALL_CAPS_VARIABLE are more likely to conflict with macros, so variables should avoid that:
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es9-avoid-all_caps-names

**Comment by senior-zero** [comment]
Hello @zasdfgbnm! I agree with you. We are trying to get away from capitalize constant names in new code ([example](https://github.com/NVIDIA/cccl/blob/4d01371f49ac9f30d5057f819b13df664e9ef945/cub/cub/device/dispatch/tuning/tuning_scan.cuh#L89-L90)). We tend to apply new style to the existing private constants when possible, but the transition of public ones is complicated because it might break someone. I noticed that you've reopened the issue. We are working on CUB in https://github.com/NVIDIA/cccl these days. If you'd like to track progress on getting rid of capitalized constant names, please, file an issue there.
